scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 5s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - localhost:9090
  - job_name: gnmic
    static_configs:
      - targets:
        - clab-gnp-stack-gnmic-ingestor:7890
        # - clab-gnp-stack-gnmic-processor:7890
        - clab-gnp-stack-gnmic-emitter:7890
  - job_name: nats
    static_configs:
      - targets:
        - clab-gnp-stack-nats-exporter:7777